name: reusable workflow
on: workflow_call #using this wf in other wf "reusable_wf_import"
jobs:
    deploy: 
        runs-on: ubuntu-latest
        steps:
            - name: download artifacts
              uses: actions/download-artifact@v3
              with:
                name: dist-files
            - name: list all files
              run: ls
            

              