name: reusable workflow
on:  #using this wf in other wf "reusable_wf_import"
    workflow_call:
        inputs:
            artifact-name:
                description: name of deployment artifact name
                default: dist
                type: string
jobs:
    deploy: 
        runs-on: ubuntu-latest
        steps:
            - name: download artifacts
              uses: actions/download-artifact@v3
              with:
                name: ${{inputs.artifact-name}}
            - name: list all files
              run: ls
            

              